info = '''
Consider a set of sequence samples
  run a set of tools to analyse the sample sequences, individually and collectively
  includes assembly into larger fragments and assess the assembly quality with busco
Inputs (in resources/ - may be linked by the get rule):
  Samples are specified by a list "samplenames" in a config file - config.yaml,
    which must exist in the working directory.
    each sample name should have 2 corresponding files for 'forward' and 'reverse' reads
      the filename patterns are
      {name}_pass_1.fastq.gz and {name}_pass_2.fastq.gz in resources/
  busco needs a reference - set by busco_refdir and busco_lineage
Outputs  are written to subdirectories in results/
  NB. stdout/stderr output goes to logs/,
       resource usage info to benchmarks/
       The rule benchmark_report will summarise benchmark outputs to benchmark.html
       which references benchmark_files/
'''

from snakemake.utils import min_version, validate
# desirable to have workflow-profile support - not strictly this min_version number
min_version("7.32.4")

snakedir = workflow.basedir

configfile: "config.yaml"
#validate(config, "config.schema.json")
samplenames = config["samplenames"]
fastq_indir = config.get("fastq_indir", "")
fasta_indir = config.get("fasta_indir", "")
bact_ref = config.get("bact_ref", "MSimiae_NZ_AP022568_1.fasta")
busco_refdir = config.get("busco_refdir", "")
busco_lineage = config.get("busco_lineage", "bacteria_odb10")

fastq_input = expand('resources/{sample}_{read_type}.fastq.gz', sample=samplenames, read_type=["pass_1", "pass_2"])

fastqc_output = expand('results/fastqc/{sample}_{read_type}_fastqc.html', sample=samplenames, read_type=["pass_1", "pass_2"])
kraken_output = expand("results/kraken/{sample}_kraken_report.txt", sample=samplenames), expand("results/kraken/{sample}_kraken_output.txt", sample=samplenames)
spades_output = expand("results/spades_assemblies/{sample}/contigs.fasta", sample=samplenames)
quast_output = expand("results/quast/{sample}/report.html", sample=samplenames)
busco_output = expand("results/busco/{sample}", sample=samplenames)
assembly_stats_output = expand("results/assembly_stats/{sample}_assembly_stats.txt",sample=samplenames)
abricate_output = expand("results/abricate/{sample}_res_ncbi.csv", sample=samplenames), expand("results/abricate/{sample}_vir.csv", sample=samplenames)
fastmlst_output = expand("results/fastmlst/{sample}_fastmlst_report.csv", sample=samplenames)
snippycore_output = "results/snippycore/core.aln"
snippyclean_output = "results/snippyclean/clean.core.aln"
snp_dists_output = "results/snp_dists/dist_matrix.tab", "results/snp_dists/dist_long.tab"
raxml_output = "results/raxml/coreT.raxml.bestTree"
clonalframe_output = "results/clonalframe/cfT.ML_sequence.fasta"
prokka_output = expand("results/prokka/{sample}",sample = samplenames)

rule all:
    '''default rule. Run entire workflow
    '''
    input:
        fastqc_output,
        f"references/{bact_ref}",
        kraken_output,
        spades_output,
        quast_output,
        busco_output,
        assembly_stats_output,
        abricate_output,
        fastmlst_output,
        snippycore_output,
        snippyclean_output,
        snp_dists_output,
        raxml_output,
        clonalframe_output,
        prokka_output

rule clean:
    '''Remove all the outputs - mostly useful when testing
    '''
    log: "logs/clean.log"
    conda: "envs/null.yaml"
    shell:
        "rm -rf results &> {log}"

rule benchmark_report:
    '''Summarise any benchmark outputs

       Assumes benchmark.qmd next to Snakefile
       Does *not* use dependencies - just run on demand
    '''
    params:
        bq = f"{snakedir}/benchmark.qmd"
    log: "logs/benchmark_report.log"
    conda: "envs/null.yaml"
    envmodules:
        "python/3.12.3",
        "quarto"
    shell:
        "cp {params.bq} benchmark.qmd; "
        "quarto render benchmark.qmd &> {log}"

rule help:
    '''Print helpful info
    '''
    log: "logs/help.log"
    run:
        print(info)

rule get:
    '''get/link inputs
    '''
    output:
        fastq_input,
        f"references/{bact_ref}"
    params:
        fastq_indir = fastq_indir,
        fasta_indir = fasta_indir,
        bact_ref = bact_ref
    log: "logs/get.log"
    conda: "envs/null.yaml"
    shell:
        """
        echo logging stdout/err to {log}
        test -n "{params.fastq_indir}" && ln -sf {params.fastq_indir}/*fastq.gz resources/ &> {log}
        test -n "{params.fasta_indir}" && ln -sf {params.fasta_indir}/{params.bact_ref} references/{params.bact_ref} &>> {log}
        """

rule fast_qc:
    '''qc check with fastqc
    '''
    input:
        "resources/{sample}_{read_type}.fastq.gz"
    output:
        zip = "results/fastqc/{sample}_{read_type}_fastqc.zip",
        html = "results/fastqc/{sample}_{read_type}_fastqc.html"
    threads: 2
    log: "logs/fastqc/{sample}_{read_type}.log"
    benchmark: "benchmarks/fastqc/{sample}_{read_type}.tsv"
    conda: "envs/null.yaml"
    envmodules: "fastqc"
    shell:
        "echo logging stdout/err to {log}; "
        "fastqc --threads {threads} --outdir results/fastqc/ {input} &> {log}"

rule kraken:
    '''classification with Kraken2
    '''
    input:
        forward = "resources/{sample}_pass_1.fastq.gz",
        rev = "resources/{sample}_pass_2.fastq.gz"
    output:
        report = "results/kraken/{sample}_kraken_report.txt",
        output = "results/kraken/{sample}_kraken_output.txt"
    threads: 32
    #resources:
    #    mem_mb=131072
    log: "logs/kraken/{sample}.log"
    benchmark: "benchmarks/kraken/{sample}.tsv"
    conda: "envs/null.yaml"
    envmodules:
        "kraken2",
        "jemalloc"
    shell:
        "echo logging stdout/err to {log}; "
        "kraken2 --threads {threads} --paired {input.forward} {input.rev} --report {output.report} --output {output.output} &> {log}"

rule assemble_spades:
    '''assemble and analyse sequences
    '''
    input:
        forward = "resources/{sample}_pass_1.fastq.gz",
        rev = "resources/{sample}_pass_2.fastq.gz"
    output:
        path = directory("results/spades_assemblies/{sample}/"),
        S1 = "results/spades_assemblies/{sample}/contigs.fasta"
    #resources:
    #    mem_mb = 64000
    threads: 8
    log: "logs/spades/{sample}.log"
    benchmark: "benchmarks/spades/{sample}.tsv"
    conda: "envs/null.yaml"
    envmodules:
        "spades",
        "jemalloc"
    shell:
        "echo logging stdout/err to {log}; "
        "spades.py -1 {input.forward} -2 {input.rev} -o {output.path} -t {threads} &> {log}"

rule quast:
    '''evaluate assembly
    '''
    input:
        contigs = "results/spades_assemblies/{sample}/contigs.fasta",
        reference = f"references/{bact_ref}"
    output:
        report = "results/quast/{sample}/report.html"
    threads: 4
    #resources:
    #    mem_mb = 16000
    log: "logs/quast/{sample}.log"
    benchmark: "benchmarks/quast/{sample}.tsv"
    conda: "envs/null.yaml"
    envmodules: "quast"
    shell:
        "echo logging stdout/err to {log}; "
        "quast.py -o results/quast/{wildcards.sample} -r {input.reference} {input.contigs} &> {log}"

rule assembly_stats:
    '''returns assembly statistics
    '''
    input:
        contigs = "results/spades_assemblies/{sample}/contigs.fasta"
    output:
        stats = "results/assembly_stats/{sample}_assembly_stats.txt"
    threads: 1
    log: "logs/assembly_stats/{sample}.log"
    benchmark: "benchmarks/assembly-stats/{sample}.tsv"
    conda: "envs/null.yaml"
    envmodules: "assembly-stats"
    shell:
        "echo logging stdout/err to {log}; "
        "assembly-stats {input.contigs} > {output.stats} &> {log}"

rule busco:
    '''identify/classify assembly
    '''
    input:
        contigs = "results/spades_assemblies/{sample}/contigs.fasta"
    output:
        path = directory("results/busco/{sample}")
    params:
        dummypath = directory("results_busco_{sample}"),
        busco_ref = f"{busco_refdir}/{busco_lineage}"
    threads: 4
    log: "logs/busco/{sample}.log"
    benchmark: "benchmarks/busco/{sample}.tsv"
    conda: "envs/null.yaml"
    envmodules: "busco"
    shell:
        "echo logging stdout/err to {log}; "
        "mkdir -p {params.dummypath} &> {log};"
        "busco --cpu {threads} -f -m genome -i {input.contigs} -l {params.busco_ref} --out {params.dummypath} -f &>> {log};"
        "rm -rf {output.path} &>> {log};"
        "mv {params.dummypath} {output.path} &>> {log}"

rule abricate:
    '''abricate
    '''
    input:
        contigs = "results/spades_assemblies/{sample}/contigs.fasta"
    output:
        res_ncbi = "results/abricate/{sample}_res_ncbi.csv",
        vir = "results/abricate/{sample}_vir.csv"
    log: "logs/abricate/{sample}_abricate.log"
    benchmark: "benchmarks/abricate/{sample}.tsv"
    threads: 4
    conda: "envs/null.yaml"
    envmodules: "abricate"
    shell:
        """
        echo logging stderr to {log}
        abricate --csv {input.contigs} > {output.res_ncbi} 2> {log}
        abricate --minid 80 --mincov 80 --csv {input.contigs} > {output.vir} 2>> {log}
        """

rule fastmlst:
    '''fastmlst
    '''
    input:
        contigs = "results/spades_assemblies/{sample}/contigs.fasta"
    output:
        report = "results/fastmlst/{sample}_fastmlst_report.csv"
    log: "logs/fastmlst/{sample}.log"
    benchmark: "benchmarks/fastmlst/{sample}.tsv"
    threads: 4
    #resources:
    #    mem_mb = 8000
    conda: "envs/null.yaml"
    envmodules: "fastmlst"
    shell:
        "echo logging stdout/err to {log}; "
        "fastmlst {input.contigs} -to {output.report} -t {threads} &> {log}"

rule snippy:
    '''snippy
    '''
    input:
        reference = f"references/{bact_ref}",
        contigs = "results/spades_assemblies/{sample}/contigs.fasta"
    output:
        dir = directory("results/snippy/{sample}/")
    log: "logs/snippy/{sample}.log"
    benchmark: "benchmarks/snippy/{sample}.tsv"
    conda: "envs/null.yaml"
    envmodules: "snippy"
    shell:
        "echo logging stdout/err to {log}; "
        "snippy --reference {input.reference} --ctgs {input.contigs} --outdir {output.dir} &> {log}"

rule snippycore:
    '''snippycore
    '''
    input:
        reference = f"references/{bact_ref}",
        snippy_dirs = expand("results/snippy/{sample}", sample=samplenames)
    output:
        path = directory("results/snippycore"),
        core = "results/snippycore/core.aln"
    threads: 8
    log: "logs/snippycore/snippycore.log"
    benchmark: "benchmarks/snippycore/snippycore.tsv"
    conda: "envs/null.yaml"
    envmodules: "snippy"
    shell:
        "echo logging stdout/err to {log}; "
        "snippy-core --ref {input.reference} --prefix {output.path}/core {input.snippy_dirs} &> {log}"

rule snippyclean:
    '''snippyclean
    '''
    input:
        core = "results/snippycore/core.aln"
    output:
        cleaned_aln = "results/snippyclean/clean.core.aln"
    threads: 2
    log: "logs/snippyclean/snippyclean.log"
    benchmark: "benchmarks/snippyclean/snippyclean.tsv"
    conda: "envs/null.yaml"
    envmodules: "snippy"
    shell:
        """
        echo logging stderr to {log}
        mkdir -p results/snippyclean/
        snippy-clean_full_aln {input.core} > {output.cleaned_aln} 2> {log}
        """

rule snp_dists:
    '''snp_dists
    '''
    input:
        core_aln = "results/snippycore/core.aln"
    output:
        snp_matrix = "results/snp_dists/dist_matrix.tab",
        snp_long = "results/snp_dists/dist_long.tab"
    threads: 2
    log: "logs/snp_dists/snp_dists.log"
    benchmark: "benchmarks/snp_dists/snp_dists.tsv"
    conda: "envs/null.yaml"
    envmodules: "snp-dists"
    shell:
        """
        echo logging stderr to {log}
        snp-dists -b {input.core_aln} > {output.snp_matrix} 2> {log}
        snp-dists -m {input.core_aln} > {output.snp_long} 2>> {log}
        """

rule raxml:
    '''raxml
    '''
    input:
        cleaned_aln = "results/snippyclean/clean.core.aln"
    output:
        path = directory("results/raxml"),
        bestTree = "results/raxml/coreT.raxml.bestTree"
    threads: 8
    log: "logs/raxml/raxml.log"
    benchmark: "benchmarks/raxml/raxml.tsv"
    conda: "envs/null.yaml"
    envmodules: "raxml-ng"
    shell:
        "echo logging stdout/err to {log}; "
        "raxml-ng --msa {input.cleaned_aln} --model GTR+G --redo --prefix {output.path}/coreT --seed 12 &> {log}"

rule clonal_frame:
    '''clonal_frame
    '''
    input:
        bestTree = "results/raxml/coreT.raxml.bestTree",
        cleaned_aln = "results/snippyclean/clean.core.aln"
    output:
        path = directory("results/clonalframe"),
        cleaned_tree = "results/clonalframe/cfT.ML_sequence.fasta"
    threads: 8
    log: "logs/clonalframe/clonalframe.log"
    benchmark: "benchmarks/clonalframe/clonalframe.tsv"
    conda: "envs/null.yaml"
    envmodules: "clonalframeml"
    shell:
        "echo logging stdout/err to {log}; "
        "ClonalFrameML {input.bestTree} {input.cleaned_aln} {output.path}/cfT &> {log}"

rule prokka:
    '''prokka
    '''
    input:
        contigs = "results/spades_assemblies/{sample}/contigs.fasta"
    output:
        annotation_dir = directory("results/prokka/{sample}")
    threads: 8
    log: "logs/prokka/{sample}/prokka.log"
    benchmark: "benchmarks/prokka/{sample}.tsv"
    conda: "envs/null.yaml"
    envmodules: "prokka"
    shell:
        "echo logging stdout/err to {log}; "
        "prokka --force {input.contigs} --outdir {output.annotation_dir} &> {log}"

"""
rule trim_galore:
    '''use qc info to trim low quality reads
    '''
    input:
        forward = "resources/{sample}_pass_1.fastq.gz",
        rev = "resources/{sample}_pass_2.fastq.gz"
    output:
        path = directory("results/trim_galore/{sample}"),
        T1 = "results/trim_galore/{sample}/{sample}_pass_1.fq.gz",
        T2 = "results/trim_galore/{sample}/{sample}_pass_2.fq.gz"
    threads: 2
    log: "logs/trim_galore/{sample}.log"
    benchmark: "benchmarks/trim_galore/{sample}.tsv"
    conda: "envs/null.yaml"
    envmodules: "trimgalore"
    shell:
        "echo logging stdout/err to {log}; "
        "trim_galore --cores {threads} --paired {input.forward} {input.rev} --fastqc -- output_dir {output.path} &> {log}"
"""
